//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Data.Oracle.ManagedDataAccess.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple.Data.Oracle.ManagedDataAccess.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select OBJECT_NAME, PACKAGE_NAME, ARGUMENT_NAME, DATA_TYPE, IN_OUT, POSITION
        ///from ALL_ARGUMENTS
        ///where owner = :1
        ///order by OBJECT_NAME, POSITION.
        /// </summary>
        internal static string procedure_args {
            get {
                return ResourceManager.GetString("procedure_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select OBJECT_NAME,PROCEDURE_NAME 
        ///from user_procedures.
        /// </summary>
        internal static string procedures {
            get {
                return ResourceManager.GetString("procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select object_name, procedure_name from all_procedures where owner=:1.
        /// </summary>
        internal static string procedures_for_schema {
            get {
                return ResourceManager.GetString("procedures_for_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select table_name, column_name, data_type, data_length from all_tab_cols where owner=:1 and table_name in (select distinct table_name from table_privileges where (grantee=:2 or grantee in (select granted_role from user_role_privs where username=:3))  and owner=:4).
        /// </summary>
        internal static string schema_columns {
            get {
                return ResourceManager.GetString("schema_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct table_name from table_privileges where (grantee=:1 or grantee in (select granted_role from user_role_privs where username=:2))  and owner=:3.
        /// </summary>
        internal static string table_access_for_schema {
            get {
                return ResourceManager.GetString("table_access_for_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select con.table_name as fk_table, con.column_name as fk_column,
        ///       rel.table_name as pk_table, rel.column_name as pk_column
        ///from user_cons_columns con 
        ///    join user_constraints cc 
        ///      on con.constraint_name = cc.constraint_name
        ///    join user_cons_columns rel 
        ///      on cc.r_constraint_name = rel.constraint_name 
        ///     and con.position = rel.position
        ///where
        ///    cc.constraint_type = &apos;R&apos;.
        /// </summary>
        internal static string table_fks {
            get {
                return ResourceManager.GetString("table_fks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT b.table_name, b.column_name, b.position, a.status, a.owner
        ///FROM all_constraints a
        ///inner join all_cons_columns b
        ///on a.owner = b.owner
        ///and a.constraint_name = b.constraint_name
        ///WHERE a.constraint_type = &apos;P&apos;
        ///AND a.owner = :1
        ///ORDER BY b.table_name, b.position.
        /// </summary>
        internal static string table_pks {
            get {
                return ResourceManager.GetString("table_pks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select table_name, column_name, data_type, data_length 
        ///from user_tab_cols
        ///where HIDDEN_COLUMN = &apos;NO&apos;.
        /// </summary>
        internal static string user_columns {
            get {
                return ResourceManager.GetString("user_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select object_name, object_type
        ///from user_objects
        ///where object_type in (&apos;VIEW&apos;,&apos;TABLE&apos;).
        /// </summary>
        internal static string user_tables_views {
            get {
                return ResourceManager.GetString("user_tables_views", resourceCulture);
            }
        }
    }
}
